/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-03-09 01:37:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.*;
import entities.*;
import java.util.LinkedList;

public final class aplicarSancion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("data");
    _jspx_imports_packages.add("entities");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"ISO-8859-1\">\r\n");
      out.write("		<title>[PSG]Aplicar Sancion</title>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body> \r\n");
      out.write("\r\n");
      out.write("		");

		int userid = 0;
		Integrante i = new Integrante();
		if (session.getAttribute("id") == null)
			response.sendRedirect("LoginTUNEADO.jsp");
		else 
		{
			userid = Integer.parseInt(session.getAttribute("id").toString());		
			i.setIdIntegrante(userid);
			
			DataIntegrante dataint = new DataIntegrante();	
			i = dataint.getByIdIntegrante(i);
		}
		
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<h2 align=\"center\">-- Sanciones --</h2> <br>\r\n");
      out.write("		<table  align=\"center\" cellspacing=\"2\" cellpadding=\"2\" border=\"2\" width =\"500\">	\r\n");
      out.write("			<tr bgcolor=blue>\r\n");
      out.write("				<th>Tipo Sancion</th>\r\n");
      out.write("				<th>Numero Sancion</th>\r\n");
      out.write("				<th>Estado de la sancion</th>\r\n");
      out.write("				<th>Fecha</th>\r\n");
      out.write("				<th>URL</th>\r\n");
      out.write("				<th>Apelada</th>\r\n");
      out.write("				<th>Elminar</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");
 
				DataSancion ds = new DataSancion();
				LinkedList<Sancion> listaS = ds.getById(i).getSancion();
				for(Sancion s :  listaS) {
			
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th> ");
      out.print(s.getTipoSancion() );
      out.write(" </th>\r\n");
      out.write("				<th> ");
      out.print(s.getNroSancion() );
      out.write(" </th>\r\n");
      out.write("				<th> \r\n");
      out.write("				");
	
					if(s.isEstado())
						out.print("Activa");
					else
						out.print("Apelada");
				
      out.write(" \r\n");
      out.write("				</th>\r\n");
      out.write("				<th> ");
      out.print(s.getFecha() );
      out.write(" </th>\r\n");
      out.write("				<th> \r\n");
      out.write("					<a href=\"");
      out.print(s.getUrlSancion());
      out.write("\" target=\"_blank\">Url imagen</a> \r\n");
      out.write("				</th>\r\n");
      out.write("				<th> \r\n");
      out.write("					<form action=\"apelarS?idSA=");
      out.print(s.getId());
      out.write("\" method=\"post\">\r\n");
      out.write("						<input type =\"submit\" value = \"Apelar\" >\r\n");
      out.write("					</form>	\r\n");
      out.write("				</th>\r\n");
      out.write("				<th> \r\n");
      out.write("					<form action=\"eliminarS?idSE=");
      out.print(s.getId());
      out.write("\" method=\"post\">\r\n");
      out.write("						<input type =\"submit\" value = \"Eliminar\" >\r\n");
      out.write("					</form>	\r\n");
      out.write("				</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("		</table><br><br>\r\n");
      out.write("	\r\n");
      out.write("		<form action=\"sancionS?idS=");
      out.print(i.getIdIntegrante() );
      out.write("\" method=\"post\">\r\n");
      out.write("			Tipo de sancion:\r\n");
      out.write("			<select name=\"tipoSancion\">\r\n");
      out.write("		        <option value=\"Raya\"> Raya </option>\r\n");
      out.write("				<option value=\"Strike\"> Strike </option>\r\n");
      out.write("	        </select><br><br>\r\n");
      out.write("	        Numero de Sancion: \r\n");
      out.write("	        <select name=\"nroSancion\">\r\n");
      out.write("		        <option value=\"1\"> 1 </option>\r\n");
      out.write("				<option value=\"2\"> 2 </option>\r\n");
      out.write("				<option value=\"3\"> 3 </option>\r\n");
      out.write("	        </select><br><br>\r\n");
      out.write("	        Motivo de la sancion: <input type = \"text\" name = \"motivo\" Required><br><br>\r\n");
      out.write("	        Imagen (opcional): <input type = \"text\" name = \"url\" Required><br><br>\r\n");
      out.write("			<input type = \"submit\" value = \"Aplicar Sancion\" Required><br>\r\n");
      out.write("		</form>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
