/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-03-10 00:02:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.*;
import entities.*;
import java.util.LinkedList;

public final class AplicarSancionTuneado_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("data");
    _jspx_imports_packages.add("entities");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html dir=\"ltr\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <!-- Tell tde browser to be responsive to screen widtd -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"widtd=device-widtd, initial-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\"\r\n");
      out.write("        content=\"wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Xtreme lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Xtreme admin lite design, Xtreme admin lite dashboard bootstrap 5 dashboard template\">\r\n");
      out.write("    <meta name=\"description\"\r\n");
      out.write("        content=\"Xtreme Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework\">\r\n");
      out.write("    <meta name=\"robots\" content=\"noindex,nofollow\">\r\n");
      out.write("    <title>Panel Listado de Robos</title>\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://www.wrappixel.com/templates/xtreme-admin-lite/\" />\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"./assets/images/favicon.png\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"./dist/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./dist/css/sanciones.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style type=\"text/css\">     \r\n");
      out.write("	.containerHome {\r\n");
      out.write("	    text-align: center;\r\n");
      out.write("	    overflow: hidden;\r\n");
      out.write("	    widtd: 80%;\r\n");
      out.write("	    margin: 0 auto;\r\n");
      out.write("	    display: table;\r\n");
      out.write("	    padding: 0 0 8em 0;\r\n");
      out.write("	 }   \r\n");
      out.write("	.AS {\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    widtd: 80%;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("	} \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("		");

		/*int userid = 0;
		Integrante i = new Integrante();
		if (session.getAttribute("id") == null)
			response.sendRedirect("LoginTUNEADO.jsp");
		else 
		{
			userid = Integer.parseInt(session.getAttribute("id").toString());		
			i.setIdIntegrante(userid);
			
			DataIntegrante dataint = new DataIntegrante();	
			i = dataint.getByIdIntegrante(i);
		}*/

		int idRol = 0;
		int userid = 0;
		Integrante usuarioOnline = new Integrante();
		
		userid = Integer.parseInt(session.getAttribute("id").toString());
		
		usuarioOnline.setIdIntegrante(userid);
		
		DataIntegrante dataint = new DataIntegrante();
		
		usuarioOnline = dataint.getByIdIntegrante(usuarioOnline);
		
		idRol = Integer.parseInt(session.getAttribute("rol").toString());

		
      out.write("\r\n");
      out.write("		\r\n");
      out.write("    <h1>\r\n");
      out.write("	    <span class=\"blue\"></span>[PSG]<span class=\"blue\"></span> \r\n");
      out.write("	    <span class=\"yellow\">Sanciones</span>\r\n");
      out.write("    \r\n");
      out.write("    </h1>       \r\n");
      out.write("        <br>\r\n");
      out.write("        <table class=\"container\" align=\"center\" cellspacing=\"2\" cellpadding=\"2\" width =\"500\">\r\n");
      out.write("                <tr bgcolor=blue>\r\n");
      out.write("                    <th><h1> Tipo Sancion</h1></th> \r\n");
      out.write("                    <th><h1> Numero Sancion</h1></th>\r\n");
      out.write("                    <th><h1>Estado de la sancion</h1></th>\r\n");
      out.write("                    <th><h1>Fecha</h1></th>\r\n");
      out.write("                    <th><h1>URL</h1></th>\r\n");
      out.write("                    <th><h1>Apelada</h1></th>\r\n");
      out.write("                    <th><h1>Eliminar</h1></th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            \r\n");
      out.write("            ");
 
				DataSancion ds = new DataSancion();
				LinkedList<Sancion> listaS = ds.getById(i).getSancion();
				for(Sancion s :  listaS) {
			
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td> ");
      out.print(s.getTipoSancion() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print(s.getNroSancion() );
      out.write("</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                    	");
	
							if(s.isEstado())
								out.print("Activa");
							else
								out.print("Apelada");
						
      out.write(" \r\n");
      out.write("					</td>\r\n");
      out.write("                    <td> ");
      out.print(s.getFecha() );
      out.write("</td>\r\n");
      out.write("                    <td> \r\n");
      out.write("                    	<a href=\"");
      out.print(s.getUrlSancion());
      out.write("\" target=\"_blank\">Url imagen</a> \r\n");
      out.write("                   	</td>\r\n");
      out.write("                    <td> \r\n");
      out.write("                    	<form action=\"apelarS?idSA=");
      out.print(s.getId());
      out.write("\" metdod=\"post\">\r\n");
      out.write("							<input type =\"submit\" value = \"Apelar\" >\r\n");
      out.write("						</form>	\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td> \r\n");
      out.write("	                    <form action=\"eliminarS?idSE=");
      out.print(s.getId());
      out.write("\" metdod=\"post\">\r\n");
      out.write("							<input type =\"submit\" value = \"Eliminar\" >\r\n");
      out.write("						</form>	\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            ");

				}
			
      out.write("                \r\n");
      out.write("        </table>\r\n");
      out.write("        \r\n");
      out.write("            </br></br>\r\n");
      out.write("            \r\n");
      out.write("        <form action=\"sancionS?idS=");
      out.print(i.getIdIntegrante() );
      out.write("\" metdod=\"post\">\r\n");
      out.write("			&nbsp;&nbsp;Tipo de sancion:\r\n");
      out.write("			<select name=\"tipoSancion\">\r\n");
      out.write("		        <option value=\"Raya\"> Raya </option>\r\n");
      out.write("				<option value=\"Strike\"> Strike </option>\r\n");
      out.write("	        </select><br><br>\r\n");
      out.write("	        &nbsp;&nbsp;Numero de Sancion: \r\n");
      out.write("	        <select name=\"nroSancion\">\r\n");
      out.write("		        <option value=\"1\"> 1 </option>\r\n");
      out.write("				<option value=\"2\"> 2 </option>\r\n");
      out.write("				<option value=\"3\"> 3 </option>\r\n");
      out.write("	        </select><br><br>\r\n");
      out.write("	        &nbsp;&nbsp;Motivo de la sancion: <input type = \"text\" name = \"motivo\" Required><br><br>\r\n");
      out.write("	        &nbsp;&nbsp;Imagen (opcional): <input type = \"text\" name = \"url\" Required><br><br>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"AS\">\r\n");
      out.write("              &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; <input type = \"submit\" value = \"Aplicar Sancion\" Required><br>\r\n");
      out.write("            </div>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("		</br></br>\r\n");
      out.write("        <div class=\"containerHome\">\r\n");
      out.write("            <a button type=\"button\" class=\"btn btn-outline-danger\" href=\"HomeTuneada.jsp\">Home</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("            <footer class=\"footer text-center\">\r\n");
      out.write("                Panel de la faccion de Prosegur en [BA:RP] || \r\n");
      out.write("                    <a href=\"https://github.com/Luchoragusa\">Luciano Ragusa</a> || \r\n");
      out.write("                    <a href=\"https://github.com/JuaniPucheta\">Juan Ignacio Pucheta</a>.|| \r\n");
      out.write("                    <a href=\"https://githdub.com/CamiloPereyra\">Camilo Pereyra</a>.\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
