/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-03-09 23:37:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.*;
import entities.*;
import java.util.LinkedList;

public final class GestionInt_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("data");
    _jspx_imports_packages.add("entities");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>[PSG]Gestion Integrante</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./dist/css/GestionInt_1.css\">\r\n");
      out.write("    <link href=\"./dist/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./dist/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        .btn-outline-secondary {\r\n");
      out.write("            padding-right: 50px;\r\n");
      out.write("            padding-left: 50px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            background-color: #1250ce;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            left: 500px;\r\n");
      out.write("            bottom: 20px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        } \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<hr>\r\n");
      out.write("<div class=\"container bootstrap snippets bootdey\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("            <div class=\"main-box no-header clearfix\">\r\n");
      out.write("                <div class=\"main-box-body clearfix\">\r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                        <table class=\"table user-list\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr style=\"font-size:100%; background-color:#FFB731; border: 1px solid black; above=10\">\r\n");
      out.write("	                                <th>Usuario</th>\r\n");
      out.write("	                                <th>Rango</th>\r\n");
      out.write("	                                <th>Fecha ultimo ascenso</th>\r\n");
      out.write("	                                <th>SubDivision</th>\r\n");
      out.write("	                                <th>Discord ID</th>\r\n");
      out.write("	                                <th></th>\r\n");
      out.write("	                                <th></th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("									");

										LinkedList<Integrante> integrantes = new LinkedList<>();
										DataIntegrante di = new DataIntegrante();
										integrantes = di.getAll();
										for(Integrante i :  integrantes) {
									
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <img src=\"https://bootdey.com/img/Content/user_1.jpg\" alt=\"\">\r\n");
      out.write("                                        <a class=\"user-link\" href='GestionInt_2.jsp?id=");
      out.print(i.getIdIntegrante());
      out.write('\'');
      out.write('>');
      out.print(i.getNombre() + " " +  i.getApellido());
      out.write("</a>\r\n");
      out.write("                                        <span class=\"user-subhead\">Usuario/Admin</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                    	<span class=\"label label-info\" style=\"font-size:100%\">\r\n");
      out.write("                                    	");
      out.print(i.getRanInt().getRango().getNomRango() );
      out.write(" \r\n");
      out.write("                                    	</span>                                    	\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"text-center\" style=\"font-size:100%\">\r\n");
      out.write("                                    	<b>");
      out.print(i.getRanInt().getFecha_desde() );
      out.write("</b>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                    	<span class=\"label label-danger\" style=\"font-size:100%\">\r\n");
      out.write("	                                    	");

												String nSub = i.getSub().getDescripcion();
												if(nSub != null)
													out.println(nSub);
												else
													out.println("Sin Sub");									
											
      out.write(" \r\n");
      out.write("										</span>                                    	\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td style=\"width: 20%; font-size:100%\"><b>");
      out.print(i.getDiscordId() );
      out.write("</b></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("            ");

				}
			
      out.write("  \r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("            <footer class=\"footer text-center\">\r\n");
      out.write("                Panel de la faccion de Prosegur en [BA:RP] ||\r\n");
      out.write("                    <a href=\"https://github.com/Luchoragusa\">Luciano Ragusa</a> || \r\n");
      out.write("                    <a href=\"https://github.com/JuaniPucheta\">Juan Ignacio Pucheta</a>.|| \r\n");
      out.write("                    <a href=\"https://github.com/CamiloPereyra\">Camilo Pereyra</a>.\r\n");
      out.write("            </footer>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <a button type=\"button\" class=\"btn btn-outline-secondary\" href=\"HomeTuneada.jsp\">Home</a>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
