/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-03-10 18:25:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.swing.text.Document;
import java.util.Collection;
import data.*;
import entities.*;
import java.util.LinkedList;
import java.time.Duration;
import java.time.LocalTime;
import java.time.LocalDate;
import java.util.concurrent.LinkedBlockingDeque;

public final class HomeTuneada_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("data");
    _jspx_imports_packages.add("entities");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Collection");
    _jspx_imports_classes.add("java.time.Duration");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.LocalTime");
    _jspx_imports_classes.add("java.util.concurrent.LinkedBlockingDeque");
    _jspx_imports_classes.add("javax.swing.text.Document");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html dir=\"ltr\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\"\r\n");
      out.write("        content=\"wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Xtreme lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Xtreme admin lite design, Xtreme admin lite dashboard bootstrap 5 dashboard template\">\r\n");
      out.write("    <meta name=\"description\"\r\n");
      out.write("        content=\"Xtreme Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework\">\r\n");
      out.write("    <meta name=\"robots\" content=\"noindex,nofollow\">\r\n");
      out.write("    <!-- Este texto de aca es el que aparece arriba en la pestana de google -->\r\n");
      out.write("    <title>[PSG] Panel Usuario</title> \r\n");
      out.write("    <link rel=\"canonical\" href=\"https://www.wrappixel.com/templates/xtreme-admin-lite/\" />\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"./assets/images/favicon.png\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"./assets/libs/chartist/dist/chartist.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"./dist/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script src=\"//code.tidio.co/p26dt4g3heql4zxjwvkmcyecxl33ssqy.js\" async></script> \r\n");
      out.write("	<style>\r\n");
      out.write("		a.nav-item.nav-link.active:hover {color:#000000; background:#ffe635 }\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("		");

		int idRol = 0;
		int userid = 0;
		Integrante usuarioOnline = new Integrante();
		if (session.getAttribute("id") == null)
			response.sendRedirect("LoginTUNEADO.jsp");
		else 
		{
			userid = Integer.parseInt(session.getAttribute("id").toString());
			
			usuarioOnline.setIdIntegrante(userid);
			
			DataIntegrante dataint = new DataIntegrante();
			
			usuarioOnline = dataint.getByIdIntegrante(usuarioOnline);
			
			idRol = Integer.parseInt(session.getAttribute("rol").toString());
		}
		
      out.write("\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Preloader - style you can find in spinners.css -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div class=\"preloader\">\r\n");
      out.write("        <div class=\"lds-ripple\">\r\n");
      out.write("            <div class=\"lds-pos\"></div>\r\n");
      out.write("            <div class=\"lds-pos\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Main wrapper - style you can find in pages.scss -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div id=\"main-wrapper\" data-layout=\"vertical\" data-navbarbg=\"skin5\" data-sidebartype=\"full\"\r\n");
      out.write("        data-sidebar-position=\"absolute\" data-header-position=\"absolute\" data-boxed-layout=\"full\">\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Topbar header - style you can find in pages.scss -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <header class=\"topbar\" data-navbarbg=\"skin5\">\r\n");
      out.write("            <nav class=\"navbar top-navbar navbar-expand-md navbar-dark\">\r\n");
      out.write("                <div class=\"navbar-header\" data-logobg=\"skin5\">\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"oldIndex.html\">\r\n");
      out.write("                        <!-- Logo icon -->\r\n");
      out.write("                        <b class=\"logo-icon\">\r\n");
      out.write("                            <!--You can put here icon as well // <i class=\"wi wi-sunset\"></i> //-->\r\n");
      out.write("                            <!-- Dark Logo icon -->\r\n");
      out.write("                            <img src=\"./assets/images/logo-icon.png\" alt=\"homepage\" class=\"dark-logo\" />\r\n");
      out.write("                            <!-- Light Logo icon -->\r\n");
      out.write("                            <img src=\"./assets/images/logo-light-icon.png\" alt=\"homepage\" class=\"light-logo\" />\r\n");
      out.write("                        </b>\r\n");
      out.write("                        <!--End Logo icon -->\r\n");
      out.write("                        <!-- Logo text -->\r\n");
      out.write("                        <span class=\"logo-text\">\r\n");
      out.write("                            <!-- dark Logo text -->\r\n");
      out.write("                            <img src=\"./assets/images/logo-text.png\" alt=\"homepage\" class=\"dark-logo\" />\r\n");
      out.write("                            <!-- Light Logo text -->\r\n");
      out.write("                            <img src=\"./assets/images/logo-light-text.png\" class=\"light-logo\" alt=\"homepage\" />\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- End Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- This is for the sidebar toggle which is visible on mobile only -->\r\n");
      out.write("                    <a class=\"nav-toggler waves-effect waves-light d-block d-md-none\" href=\"javascript:void(0)\"><i\r\n");
      out.write("                            class=\"ti-menu ti-close\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- End Logo -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"navbar-collapse collapse\" id=\"navbarSupportedContent\" data-navbarbg=\"skin5\">\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->              \r\n");
      out.write("                        <div class=\"container h-100\">\r\n");
      out.write("                            <div class=\"d-flex justify-content-center h-100\">\r\n");
      out.write("                            <div class=\"searchbar\">\r\n");
      out.write("                                <input class=\"search_input\" type=\"text\" name=\"\" placeholder=\"Buscar...\">\r\n");
      out.write("                                <a href=\"#\" class=\"search_icon\"><i class=\"fas fa-search\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Right side toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <ul class=\"navbar-nav float-end\">\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                            <li><a href=\"LoginTUNEADO.jsp\" class=\"nav-item nav-link active\">Cerrar sesión</a></li>\r\n");
      out.write("                        </ul>  \r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Topbar header -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <aside class=\"left-sidebar\" data-sidebarbg=\"skin6\">\r\n");
      out.write("            <!-- Sidebar scroll-->\r\n");
      out.write("            <div class=\"scroll-sidebar\">\r\n");
      out.write("                <!-- Sidebar navigation-->\r\n");
      out.write("                <nav class=\"sidebar-nav\">\r\n");
      out.write("                    <ul id=\"sidebarnav\">\r\n");
      out.write("                        <!-- User Profile-->\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <!-- User Profile-->\r\n");
      out.write("                            <div class=\"user-profile d-flex no-block dropdown m-t-20\">\r\n");
      out.write(" \r\n");
      out.write("                                <div class=\"user-pic\"><img src=\"./assets/images/Prosegur.jpg\" alt=\"users\"\r\n");
      out.write("                                        class=\"light-logo\" width=\"50\" /></div>\r\n");
      out.write("                                <div class=\"user-content hide-menu m-l-10\">\r\n");
      out.write("                                    <a href=\"#\" class=\"\" id=\"Userdd\" role=\"button\"\r\n");
      out.write("                                        data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                        <h5 class=\"m-b-0 user-name font-medium\">\r\n");
      out.write("                                        \r\n");
      out.write("                                    		");
      out.print(usuarioOnline.getNombre() + " " + usuarioOnline.getApellido() );
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                        <i class=\"fa fa-angle-down\"></i></h5>\r\n");
      out.write("                                        <span class=\"op-5 user-email\">DiscordName</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("  \r\n");
      out.write("                                    <div class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"Userdd\">\r\n");
      out.write("                                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"configuracion.jsp\"><i\r\n");
      out.write("                                                class=\"ti-settings m-r-5 m-l-5\"></i>Configuración</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End User Profile-->\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Bitacora del servicio-->\r\n");
      out.write("                        <li class=\"p-15 m-t-10\"><a href=\"BitacoraTuneado.jsp\"\r\n");
      out.write("                                class=\"btn d-block w-100 create-btn text-white no-block d-flex align-items-center\"><i\r\n");
      out.write("                                    class=\"fa fa-plus-square\"></i> <span class=\"hide-menu m-l-5\">Panel Bitácora</span> </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- Son todas las opciones del costado a la izq-->\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                                href=\"HomeTuneada.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-home\"></i><span\r\n");
      out.write("                                    class=\"hide-menu\">Home</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                            href=\"registrarLugarRobo.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-bank\"></i><span\r\n");
      out.write("                                class=\"hide-menu\">Robo</span></a>\r\n");
      out.write("                        </li>           \r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                                href=\"miPerfilTUNEADO.jsp\" aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"mdi mdi-account-network\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Mi Perfil</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                            href=\"AplicarSancionTuneado.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-note-text\" ></i><span\r\n");
      out.write("                                class=\"hide-menu\">Sanciones</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                            href=\"RegistrarStockArmaTUNEADO.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-pistol\" ></i><span\r\n");
      out.write("                                class=\"hide-menu\">Mis armas</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        		");

								if (idRol == 1)
								
      out.write("\r\n");
      out.write("								<li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                            		href=\"AltaIntegranteTuneado.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-account-edit\"></i><span\r\n");
      out.write("                                	class=\"hide-menu\">Alta Integrante</span></a>\r\n");
      out.write("                        		</li>\r\n");
      out.write("                        \r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                            href=\"GestionInt_1.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-account-check\"></i><span\r\n");
      out.write("                                class=\"hide-menu\">Gestion Integrante</span></a>\r\n");
      out.write("                        </li>                                \r\n");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- End Sidebar navigation -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Sidebar scroll-->\r\n");
      out.write("        </aside>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <div class=\"page-wrapper\">\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Tabla del inicio (psg en servicio) -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- column -->\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <!-- Titulo -->\r\n");
      out.write("                                <div class=\"d-md-flex\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <h3 class=\"card-text\">[PSG EN SERVICO]</h3>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                <!-- Listado -->                           \r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table v-middle\">\r\n");
      out.write("                                        <tr class=\"bg-light\">\r\n");
      out.write("                                            <th class=\"border-top-0\">Nombre y Apellido</th>\r\n");
      out.write("                                            <th class=\"border-top-0\">Rango</th>\r\n");
      out.write("                                            <th class=\"border-top-0\">Tiempo en servicio</th>\r\n");
      out.write("                                            <th class=\"border-top-0\">Hora de ingreso</th>\r\n");
      out.write("                                            <th class=\"border-top-0\">Subdivision</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    ");

										LinkedList<Integrante> uActivos = new LinkedList<>();
										DataIntegrante di = new DataIntegrante();
										uActivos = di.getServicio();
										for(Integrante entry :  uActivos) {
									
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>\r\n");
      out.write("\r\n");
      out.write("                                                        		");
      out.print(entry.getNombre() + " " + entry.getApellido() );
      out.write("\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td>");
      out.print(entry.getRanInt().getRango().getNomRango() );
      out.write("</td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                            	");

                                            		Hora hr = entry.getHora().getFirst();
													out.print(entry.getHora().getFirst().getHoraInicio()); 
												
      out.write("\r\n");
      out.write("											</td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                            	");
 
													LocalDate fecha = LocalDate.now();
													LocalTime tServicio;
													Duration diferencia = Duration.between(hr.getHoraInicio(), LocalTime.now());
													if (fecha.getDayOfMonth() == hr.getFechaInicio().getDayOfMonth())
												        tServicio = LocalTime.of(diferencia.toHoursPart(), diferencia.toMinutesPart());
													else
													{
														out.println(diferencia.toHoursPart() + " " +  diferencia.toMinutesPart());
														if (diferencia.toMinutesPart()>= -5)
														{
															//out.print("se elimina la tuplaDateTime");
															DataHoras dh = new DataHoras();
															hr.setIdIntegrante(entry.getIdIntegrante());
															dh.remove(hr);
														}
														else
															tServicio = LocalTime.of(diferencia.toHoursPart()+23, diferencia.toMinutesPart()+59);
														tServicio = null; // dsp borrar esto
													}
													out.println(tServicio);
											     
      out.write("\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <label class=\"label label-danger\">\r\n");
      out.write("                                                		");

															String nSub = entry.getSub().getDescripcion();
															if(nSub != null)
																out.println(nSub);
															else
																out.println("Sin Sub");
														
      out.write("\r\n");
      out.write("												</label>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr> \r\n");
      out.write("                                        ");

											}
										
      out.write("                          \r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Table -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Robos recientes ? -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("\r\n");
      out.write("                <!-- SANCIONES -->\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Start Page Content -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <div class=\"row\">                                        \r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h4 class=\"card-title\">Listado de robos del equipo PSG</h4>\r\n");
      out.write("                                    <h5 class=\"card-subtitle\">En esta sección se mostrarían los robos hechos por equipo</h5>\r\n");
      out.write("                                    <!-- <h6 class=\"card-subtitle\">Formato de tabla tipo <code>.table-striped \"Striped rows\"</code></h6> -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"table-responsive\">\r\n");
      out.write("                                    <table class=\"table table-striped\">\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"col\">Orden de robos</th>\r\n");
      out.write("                                                <th scope=\"col\">Lugar</th>\r\n");
      out.write("                                                <th scope=\"col\">Dinero recaudado</th>\r\n");
      out.write("                                                <th scope=\"col\">Resultado</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">1</th>\r\n");
      out.write("                                                <td>Kiosco</td>\r\n");
      out.write("                                                <td>$1500</td>\r\n");
      out.write("                                                <td>Exitoso</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">2</th>\r\n");
      out.write("                                                <td>Bar</td>\r\n");
      out.write("                                                <td>$15.000</td>\r\n");
      out.write("                                                <td>Exitoso</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"row\">3</th>\r\n");
      out.write("                                                <td>Banco Nación</td>\r\n");
      out.write("                                                <td>$0</td>\r\n");
      out.write("                                                <td>Fracaso</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>                                                            \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- End PAge Content -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Right sidebar -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- .right-sidebar -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- End Right sidebar -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Recent comment and chats -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <footer class=\"footer text-center\">\r\n");
      out.write("                Panel de la faccion de Prosegur en [BA:RP] ||\r\n");
      out.write("                    <a href=\"https://github.com/Luchoragusa\">Luciano Ragusa</a> || \r\n");
      out.write("                    <a href=\"https://github.com/JuaniPucheta\">Juan Ignacio Pucheta</a>.|| \r\n");
      out.write("                    <a href=\"https://github.com/CamiloPereyra\">Camilo Pereyra</a>.\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End Wrapper -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- All Jquery -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <script src=\"./assets/libs/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap tether Core JavaScript -->\r\n");
      out.write("    <script src=\"./assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"./dist/js/app-style-switcher.js\"></script>\r\n");
      out.write("    <!--Wave Effects -->\r\n");
      out.write("    <script src=\"./dist/js/waves.js\"></script>\r\n");
      out.write("    <!--Menu sidebar -->\r\n");
      out.write("    <script src=\"./dist/js/sidebarmenu.js\"></script>\r\n");
      out.write("    <!--Custom JavaScript -->\r\n");
      out.write("    <script src=\"./dist/js/custom.js\"></script>\r\n");
      out.write("    <!--This page JavaScript -->\r\n");
      out.write("    <!--chartis chart-->\r\n");
      out.write("    <script src=\"./assets/libs/chartist/dist/chartist.min.js\"></script>\r\n");
      out.write("    <script src=\"./assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js\"></script>\r\n");
      out.write("    <script src=\"./dist/js/pages/dashboards/dashboard1.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
