/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-03-04 01:28:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entities.*;
import data.*;
import java.time.Duration;
import java.time.LocalTime;
import java.util.LinkedList;

public final class miPerfilTUNEADO_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("data");
    _jspx_imports_packages.add("entities");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.Duration");
    _jspx_imports_classes.add("java.time.LocalTime");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\"\r\n");
      out.write("        content=\"wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Xtreme lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Xtreme admin lite design, Xtreme admin lite dashboard bootstrap 5 dashboard template\">\r\n");
      out.write("    <meta name=\"description\"\r\n");
      out.write("        content=\"Xtreme Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework\">\r\n");
      out.write("    <meta name=\"robots\" content=\"noindex,nofollow\">\r\n");
      out.write("    <title>[PSG]Panel Mi Perfil</title>\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://www.wrappixel.com/templates/xtreme-admin-lite/\" />\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"./assets/images/favicon.png\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"./dist/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./dist/css/entrarsalir.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script src=\"//code.tidio.co/p26dt4g3heql4zxjwvkmcyecxl33ssqy.js\" async></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    .whos-speaking-area .speakers {\r\n");
      out.write("    -webkit-transition: all 0.4s;\r\n");
      out.write("    -o-transition: all 0.4s;\r\n");
      out.write("    transition: all 0.4s;\r\n");
      out.write("    border: 1px solid #dee2e6;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers:hover {\r\n");
      out.write("    -webkit-box-shadow: 0 0 6px 5px #ddd;\r\n");
      out.write("    box-shadow: 0 0 6px 5px #ddd;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    -webkit-transition: all 0.4s;\r\n");
      out.write("    -o-transition: all 0.4s;\r\n");
      out.write("    transition: all 0.4s;\r\n");
      out.write("    border: 1px solid #dee2e6;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img:before {\r\n");
      out.write("    background: rgba(91, 69, 213, 0.8);\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    -webkit-transform: scale(0);\r\n");
      out.write("    -ms-transform: scale(0);\r\n");
      out.write("    transform: scale(0);\r\n");
      out.write("    -webkit-transition: all 0.4s;\r\n");
      out.write("    -o-transition: all 0.4s;\r\n");
      out.write("    transition: all 0.4s;\r\n");
      out.write("    z-index: 5;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img:hover:before {\r\n");
      out.write("    -webkit-transform: scale(1);\r\n");
      out.write("    -ms-transform: scale(1);\r\n");
      out.write("    transform: scale(1);\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-top-left-radius: 6px;\r\n");
      out.write("    border-top-right-radius: 6px;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img ul {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    top: 35%;\r\n");
      out.write("    left: 40%;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    line-height: 3;\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("    -webkit-transition: all 0.4s;\r\n");
      out.write("    -o-transition: all 0.4s;\r\n");
      out.write("    transition: all 0.4s;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img ul:before {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    height: 110px;\r\n");
      out.write("    width: 110px;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    top: -15%;\r\n");
      out.write("    left: -15px;\r\n");
      out.write("    border: 1px solid #fff;\r\n");
      out.write("    -webkit-transform: rotate(44deg) scale(1.4);\r\n");
      out.write("    -ms-transform: rotate(44deg) scale(1.4);\r\n");
      out.write("    transform: rotate(44deg) scale(1.4);\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("    -webkit-transition: all 0.4s;\r\n");
      out.write("    -o-transition: all 0.4s;\r\n");
      out.write("    transition: all 0.4s;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img ul li {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin: 0 3px;\r\n");
      out.write("    -webkit-transform: perspective(50px) rotatey(80deg);\r\n");
      out.write("    transform: perspective(50px) rotatey(80deg);\r\n");
      out.write("    -webkit-transition: all 0.5s ease 0.2s;\r\n");
      out.write("    -o-transition: all 0.5s ease 0.2s;\r\n");
      out.write("    transition: all 0.5s ease 0.2s;\r\n");
      out.write("    margin: 0 5px;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img ul li a i.fa {\r\n");
      out.write("    color: rgba(255, 78, 0, 0.8);\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    -webkit-transition: all 0.4s;\r\n");
      out.write("    -o-transition: all 0.4s;\r\n");
      out.write("    transition: all 0.4s;\r\n");
      out.write("    width: 28px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    height: 28px;\r\n");
      out.write("    line-height: 21px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img ul li a i.fa:hover {\r\n");
      out.write("    color: #cf057c;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img ul li:nth-child(1) {\r\n");
      out.write("    -webkit-transform: translate3d(-53px, -50px, 0);\r\n");
      out.write("    transform: translate3d(-53px, -50px, 0);\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img ul li:nth-child(2) {\r\n");
      out.write("    -webkit-transform: translate3d(53px, -50px, 0);\r\n");
      out.write("    transform: translate3d(53px, -50px, 0);\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img ul li:nth-child(3) {\r\n");
      out.write("    -webkit-transform: translate3d(-53px, 50px, 0);\r\n");
      out.write("    transform: translate3d(-53px, 50px, 0);\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img ul li:nth-child(4) {\r\n");
      out.write("    -webkit-transform: translate3d(53px, 50px, 0);\r\n");
      out.write("    transform: translate3d(53px, 50px, 0);\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img:hover ul {\r\n");
      out.write("    left: 35%;\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("    z-index: 9;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img:hover ul:before {\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("    -webkit-transform: rotate(44deg) scale(1);\r\n");
      out.write("    -ms-transform: rotate(44deg) scale(1);\r\n");
      out.write("    transform: rotate(44deg) scale(1);\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-img:hover ul li:nth-child(1),\r\n");
      out.write(".whos-speaking-area .speakers .spk-img:hover ul li:nth-child(2),\r\n");
      out.write(".whos-speaking-area .speakers .spk-img:hover ul li:nth-child(3),\r\n");
      out.write(".whos-speaking-area .speakers .spk-img:hover ul li:nth-child(4) {\r\n");
      out.write("    -webkit-transform: translate3d(0, 0, 0);\r\n");
      out.write("    transform: translate3d(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-info {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 30px 0;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-info h3 {\r\n");
      out.write("    color: #252525;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    line-height: 20px;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("    -webkit-transition: all 0.4s;\r\n");
      out.write("    -o-transition: all 0.4s;\r\n");
      out.write("    transition: all 0.4s;\r\n");
      out.write("    text-transform: capitalize;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-info h3:hover {\r\n");
      out.write("    color: #4125dd;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area .speakers .spk-info p {\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("    color: #656565;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".whos-speaking-area-two .title-text h2 {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".whos-speaking-area-two .speakers {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers:hover img {\r\n");
      out.write("    -webkit-transform: translate3d(0px, 0px, 0px);\r\n");
      out.write("    transform: translate3d(0px, 0px, 0px);\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers img {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    -webkit-transform: translate3d(0px, 0px, 0px);\r\n");
      out.write("    transform: translate3d(0px, 0px, 0px);\r\n");
      out.write("    -webkit-transition: all 0.3s linear 0s;\r\n");
      out.write("    -o-transition: all 0.3s linear 0s;\r\n");
      out.write("    transition: all 0.3s linear 0s;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers .img-overlay {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("    background: rgba(91, 69, 213, 0.9);\r\n");
      out.write("    -webkit-transition: all 0.3s ease 0s;\r\n");
      out.write("    -o-transition: all 0.3s ease 0s;\r\n");
      out.write("    transition: all 0.3s ease 0s;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers:hover .img-overlay {\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers .name a {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: -20%;\r\n");
      out.write("    left: 10%;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    text-transform: capitalize;\r\n");
      out.write("    -webkit-transition: all 0.4s;\r\n");
      out.write("    -o-transition: all 0.4s;\r\n");
      out.write("    transition: all 0.4s;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers .name a:hover {\r\n");
      out.write("    color: #cf057c;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers:hover .name a {\r\n");
      out.write("    bottom: 10%;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers .social-icons {\r\n");
      out.write("    display: -webkit-box;\r\n");
      out.write("    display: -ms-flexbox;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 23%;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    -webkit-transition: all 0.4s;\r\n");
      out.write("    -o-transition: all 0.4s;\r\n");
      out.write("    transition: all 0.4s;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers .social-icons li {\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers .social-icons li a {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers .social-icons li a:hover {\r\n");
      out.write("    color: #252525;\r\n");
      out.write("}\r\n");
      out.write(".whos-speaking-area-two .speakers:hover .social-icons {\r\n");
      out.write("    left: 27px;\r\n");
      out.write("}\r\n");
      out.write("ul {\r\n");
      out.write("    list-style: outside none none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write(".mb50 {\r\n");
      out.write("    margin-bottom: 50px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("		");

			if (session.getAttribute("id") == null)
				response.sendRedirect("LoginTUNEADO.jsp");
		
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		");
 
			DataIntegrante di = new DataIntegrante();
			Integrante i = new Integrante();
			i.setIdIntegrante((int)session.getAttribute("id"));
			i = di.getByIdIntegrante(i);
		
      out.write("\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Preloader - style you can find in spinners.css -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div class=\"preloader\">\r\n");
      out.write("        <div class=\"lds-ripple\">\r\n");
      out.write("            <div class=\"lds-pos\"></div>\r\n");
      out.write("            <div class=\"lds-pos\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Main wrapper - style you can find in pages.scss -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div id=\"main-wrapper\" data-layout=\"vertical\" data-navbarbg=\"skin5\" data-sidebartype=\"full\"\r\n");
      out.write("        data-sidebar-position=\"absolute\" data-header-position=\"absolute\" data-boxed-layout=\"full\">\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Topbar header - style you can find in pages.scss -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <header class=\"topbar\" data-navbarbg=\"skin5\">\r\n");
      out.write("            <nav class=\"navbar top-navbar navbar-expand-md navbar-dark\">\r\n");
      out.write("                <div class=\"navbar-header\" data-logobg=\"skin5\">\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"HomeTuneada.jsp\">\r\n");
      out.write("                        <!-- Logo icon -->\r\n");
      out.write("                        <b class=\"logo-icon\">\r\n");
      out.write("                            <!--You can put here icon as well // <i class=\"wi wi-sunset\"></i> //-->\r\n");
      out.write("                            <!-- Dark Logo icon -->\r\n");
      out.write("                            <img src=\"./assets/images/logo-icon.png\" alt=\"homepage\" class=\"dark-logo\" />\r\n");
      out.write("                            <!-- Light Logo icon -->\r\n");
      out.write("                            <img src=\"./assets/images/logo-light-icon.png\" alt=\"homepage\" class=\"light-logo\" />\r\n");
      out.write("                        </b>\r\n");
      out.write("                        <!--End Logo icon -->\r\n");
      out.write("                        <!-- Logo text -->\r\n");
      out.write("                        <span class=\"logo-text\">\r\n");
      out.write("                            <!-- dark Logo text -->\r\n");
      out.write("                            <img src=\"./assets/images/logo-text.png\" alt=\"homepage\" class=\"dark-logo\" />\r\n");
      out.write("                            <!-- Light Logo text -->\r\n");
      out.write("                            <img src=\"./assets/images/logo-light-text.png\" class=\"light-logo\" alt=\"homepage\" />\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- End Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- This is for the sidebar toggle which is visible on mobile only -->\r\n");
      out.write("                    <a class=\"nav-toggler waves-effect waves-light d-block d-md-none\" href=\"javascript:void(0)\"><i\r\n");
      out.write("                            class=\"ti-menu ti-close\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- End Logo -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"navbar-collapse collapse\" id=\"navbarSupportedContent\" data-navbarbg=\"skin5\">\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <div class=\"container h-100\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-center h-100\">\r\n");
      out.write("                        <div class=\"searchbar\">\r\n");
      out.write("                            <input class=\"search_input\" type=\"text\" name=\"\" placeholder=\"Buscar...\">\r\n");
      out.write("                            <a href=\"#\" class=\"search_icon\"><i class=\"fas fa-search\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Right side toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <ul class=\"navbar-nav float-end\">\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                                <img src=\"./assets/images/users/lucho.jpg\" alt=\"user\" class=\"rounded-circle\" width=\"31\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu dropdown-menu-end user-dd animated\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"miPerfilTUNEADO.jsp\"><i class=\"ti-user m-r-5 m-l-5\"></i>\r\n");
      out.write("                                    Mi perfil</a>\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"registrarStockArmaTUNEADO.jsp\"><i class=\"ti-wallet m-r-5 m-l-5\"></i>\r\n");
      out.write("                                    Mi inventario</a>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Topbar header -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <aside class=\"left-sidebar\" data-sidebarbg=\"skin6\">\r\n");
      out.write("            <!-- Sidebar scroll-->\r\n");
      out.write("            <div class=\"scroll-sidebar\">\r\n");
      out.write("                <!-- Sidebar navigation-->\r\n");
      out.write("                <nav class=\"sidebar-nav\">\r\n");
      out.write("                    <ul id=\"sidebarnav\">\r\n");
      out.write("                        <!-- User Profile-->\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <!-- User Profile-->\r\n");
      out.write("                            <div class=\"user-profile d-flex no-block dropdown m-t-20\">\r\n");
      out.write("                                <div class=\"user-pic\"><img src=\"./assets/images/users/lucho.jpg\" alt=\"users\"\r\n");
      out.write("                                        class=\"rounded-circle\" width=\"40\" /></div>\r\n");
      out.write("                                <div class=\"user-content hide-menu m-l-10\">\r\n");
      out.write("                                    <a href=\"#\" class=\"\" id=\"Userdd\" role=\"button\"\r\n");
      out.write("                                        data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                        <h5 class=\"m-b-0 user-name font-medium\">Luciano Ragusa <i\r\n");
      out.write("                                                class=\"fa fa-angle-down\"></i></h5>\r\n");
      out.write("                                        <span class=\"op-5 user-email\">DiscordName</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <div class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"Userdd\">\r\n");
      out.write("                                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"settings.html\"><i\r\n");
      out.write("                                                class=\"ti-settings m-r-5 m-l-5\"></i>Configuración</a>\r\n");
      out.write("                                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"usted_esta_seguro.html\"><i\r\n");
      out.write("                                                class=\"fa fa-power-off m-r-5 m-l-5\"></i>Cerrar sesión</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                        <!-- Bitacora del servicio-->\r\n");
      out.write("                        <li class=\"p-15 m-t-10\"><a href=\"BitacoraTuneado.jsp\"\r\n");
      out.write("                                class=\"btn d-block w-100 create-btn text-white no-block d-flex align-items-center\"><i\r\n");
      out.write("                                    class=\"fa fa-plus-square\"></i> <span class=\"hide-menu m-l-5\">Panel Bitácora</span> </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- Son todas las opciones del costado a la izq-->\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                                href=\"HomeTuneada.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-home\"></i><span\r\n");
      out.write("                                    class=\"hide-menu\">Home</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                            href=\"registrarLugarRobo.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-bank\"></i><span\r\n");
      out.write("                                class=\"hide-menu\">Robo</span></a>\r\n");
      out.write("                        </li>           \r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                                href=\"miPerfilTUNEADO.jsp\" aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"mdi mdi-account-network\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Mi Perfil</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                            href=\"aplicarSancion.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-note-text\" ></i><span\r\n");
      out.write("                                class=\"hide-menu\">Sanciones</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                            href=\"RegistrarStockArmaTUNEADO.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-pistol\" ></i><span\r\n");
      out.write("                                class=\"hide-menu\">Mis armas</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                            href=\"AltaIntegranteTuneado.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-account-edit\"></i><span\r\n");
      out.write("                                class=\"hide-menu\">Alta Integrante</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\"> <a class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("                            href=\"GestionInt_1.jsp\" aria-expanded=\"false\"><i class=\"mdi mdi-account-check\"></i><span\r\n");
      out.write("                                class=\"hide-menu\">Gestion Integrante</span></a>\r\n");
      out.write("                        </li>      \r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- End Sidebar navigation -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Sidebar scroll-->\r\n");
      out.write("        </aside>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <div class=\"page-wrapper\">\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Bread crumb and right sidebar toggle -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"page-breadcrumb\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-5\">\r\n");
      out.write("                        <h4 class=\"page-title\">Perfil</h4>\r\n");
      out.write("                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                            <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                                <ol class=\"breadcrumb\">\r\n");
      out.write("                                    <li class=\"breadcrumb-item\"><a href=\"HomeTuneada.jsp\">Home</a></li>\r\n");
      out.write("                                    <li class=\"breadcrumb-item active\" aria-current=\"page\">Library</li>\r\n");
      out.write("                                </ol>\r\n");
      out.write("                            </nav>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End Bread crumb and right sidebar toggle -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Start Page Content -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Row -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- Column -->\r\n");
      out.write("                    <div class=\"col-lg-4 col-xlg-3 col-md-5\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"preview text-center\">\r\n");
      out.write("                                        <img class=\"preview-img\" src=\"http://simpleicon.com/wp-content/uploads/account.png\" alt=\"Preview Image\" width=\"200\" height=\"200\"/>\r\n");
      out.write("                                        <div class=\"browse-button\">\r\n");
      out.write("                                            <i class=\"fa fa-pencil-alt\"></i>\r\n");
      out.write("                                            <input class=\"browse-input\" type=\"file\" required name=\"UploadedFile\" id=\"UploadedFile\"/>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span class=\"Error\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4 class=\"card-title m-t-10\">");
      out.print(i.getNombre() + " " + i.getApellido());
      out.write("</h4>\r\n");
      out.write("\r\n");
      out.write("                            </div>                          \r\n");
      out.write("                            <div>\r\n");
      out.write("                                <hr>\r\n");
      out.write("                            </div>\r\n");
      out.write("                      <div class=\"card-body\">                      \r\n");
      out.write("						<h2 align=\"center\">-- Sanciones --</h2>\r\n");
      out.write("							<table  align=\"center\" cellspacing=\"2\" cellpadding=\"2\" border=\"2\" width =\"500\">	\r\n");
      out.write("								<tr bgcolor=blue>\r\n");
      out.write("									<th>Tipo Sancion</th>\r\n");
      out.write("									<th>Numero Sancion</th>\r\n");
      out.write("									<th>Estado de la sancion</th>\r\n");
      out.write("									<th>Fecha</th>\r\n");
      out.write("									<th>URL</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("								");
 
									LinkedList<Sancion> listaS = i.getSancion();
									String url;
									for(Sancion s :  listaS) {
										url = s.getUrlSancion();
								
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th> ");
      out.print(s.getTipoSancion() );
      out.write(" </th>\r\n");
      out.write("									<th> ");
      out.print(s.getNroSancion() );
      out.write(" </th>\r\n");
      out.write("									<th> \r\n");
      out.write("									");
	
										if(s.isEstado())
											out.print("Activa");
										else
											out.print("Apelada");
									
      out.write(" \r\n");
      out.write("									</th>\r\n");
      out.write("									<th> ");
      out.print(s.getFecha() );
      out.write(" </th>\r\n");
      out.write("									<th> \r\n");
      out.write("										<a href=\"");
      out.print(s.getUrlSancion());
      out.write("\" target=\"_blank\">Url imagen</a> \r\n");
      out.write("									</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("								");

									}
								
      out.write("\r\n");
      out.write("							</table><br>\r\n");
      out.write("							\r\n");
      out.write("							<h2 align=\"center\">-- Bitacoras --</h2>\r\n");
      out.write("							<table  align=\"center\" cellspacing=\"2\" cellpadding=\"2\" border=\"2\" width =\"500\">	\r\n");
      out.write("												<tr bgcolor=grey>\r\n");
      out.write("													<th>Hora Inicio</th>\r\n");
      out.write("													<th>Fecha Inicio</th>\r\n");
      out.write("													<th>horaFin</th>\r\n");
      out.write("													<th>Fecha Fin</th>	\r\n");
      out.write("													<th>Horas Jugadas</th>		\r\n");
      out.write("												</tr>\r\n");
      out.write("												");

													LinkedList<Hora> horas = i.getHora();	
													for(Hora h :  horas) {
												
      out.write("\r\n");
      out.write("													<tr>\r\n");
      out.write("														<th> ");
      out.print(h.getHoraInicio() );
      out.write(" </th>\r\n");
      out.write("														<th> ");
      out.print(h.getFechaInicio() );
      out.write(" </th>\r\n");
      out.write("														<th> ");
      out.print(h.getHoraFin() );
      out.write(" </th>\r\n");
      out.write("														<th> ");
      out.print(h.getFechaFin() );
      out.write(" </th>\r\n");
      out.write("														<th> ");
      out.print(h.getHorasJugadas() );
      out.write(" </th>\r\n");
      out.write("												   </tr>\r\n");
      out.write("												");

													}
												
      out.write("\r\n");
      out.write("												");
	
													LocalTime contadorHorasJugadas = LocalTime.of(0, 0);
													for(Hora h :  horas) 
													{
														if (h.getHorasJugadas() != null)
														{
															contadorHorasJugadas = contadorHorasJugadas.plusHours(h.getHorasJugadas().getHour())
																	.plusMinutes(h.getHorasJugadas().getMinute())
																	.plusSeconds(h.getHorasJugadas().getSecond());
														}
													}
												
      out.write("\r\n");
      out.write("											</table><br>\r\n");
      out.write("									<label class=\"col-md-12\" style=\"color: blue\">\r\n");
      out.write("                                    	<p style = \"font-family:themify;font-size:19px;font-style:normal;\"> Horas totales:</p> \r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <p style = \"font-family:themify;font-size:19px;font-style:normal;\">\r\n");
      out.write("                                    	");
 out.println(contadorHorasJugadas); 
      out.write("\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <label class=\"col-md-12\" style=\"color: blue\">\r\n");
      out.write("										<p style = \"font-family:themify;font-size:19px;font-style:normal;\">Progreso de la semana:</p> \r\n");
      out.write("									</label>\r\n");
      out.write("									<progress align=\"center\" id=\"horasSemana\" \r\n");
      out.write("										max=\"720\"\r\n");
      out.write("										value=\"\r\n");
      out.write("												");
 
												out.print(contadorHorasJugadas.getHour()*60 + contadorHorasJugadas.getMinute());
												
      out.write("\">\r\n");
      out.write("									</progress>\r\n");
      out.write("									\r\n");
      out.write("									");
 
										DataRobo dr = new DataRobo();
										LinkedList<Integer> por = dr.getPorcentaje(i);
									
      out.write("\r\n");
      out.write("									<label class=\"col-md-12\" style=\"color: blue\">\r\n");
      out.write("										<p style = \"font-family:themify;font-size:19px;font-style:normal;\">Porcentaje de robos ganados:</p>\r\n");
      out.write("									</label>\r\n");
      out.write("									\r\n");
      out.write("									<progress align=\"center\" id=\"robos\" \r\n");
      out.write("										max=\"");
      out.print(por.get(0));
      out.write("\"\r\n");
      out.write("										value=\"");
      out.print(por.get(1));
      out.write("\">\r\n");
      out.write("									</progress><br><br>\r\n");
      out.write("                                <div class=\"map-box\">\r\n");
      out.write("                                    <iframe\r\n");
      out.write("                                        src=\"https://www.google.com/maps?q=Rosario%2C%20Provincia%20de%20Santa%20Fe%2C%20Argentina&z=8&t=&ie=UTF8&output=embed\"\r\n");
      out.write("                                        width=\"100%\" height=\"150\" frameborder=\"0\" style=\"border:0\"\r\n");
      out.write("                                        allowfullscreen></iframe>\r\n");
      out.write("                                </div>                                 \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Column -->\r\n");
      out.write("                    <!-- Column -->\r\n");
      out.write("                    <div class=\"col-lg-8 col-xlg-9 col-md-7\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <form class=\"form-horizontal form-material mx-2\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-md-12\" style=\"color: blue\">\r\n");
      out.write("                                        	<p style = \"font-family:themify;font-size:19px;font-style:normal;\">Nombre completo</p>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <div class=\"col-md-12\">                                            \r\n");
      out.write("                                            <div class=\"form-control form-control-line\">\r\n");
      out.write("                                            	");
      out.print(i.getNombre() + " " + i.getApellido() );
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                     	<label class=\"col-md-12\" style=\"color: blue\">\r\n");
      out.write("                                        	<p style = \"font-family:themify;font-size:19px;font-style:normal;\">Rango</p>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <div class=\"col-md-12\"> \r\n");
      out.write("                                            <div class=\"form-control form-control-line\">\r\n");
      out.write("                                            	");
      out.print(i.getRanInt().getRango().getNomRango() );
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-md-12\" style=\"color: blue\">\r\n");
      out.write("                                        	<p style = \"font-family:themify;font-size:19px;font-style:normal;\">Fecha Ultimo Ascenso</p>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <div class=\"col-md-12\">\r\n");
      out.write("                                            <div class=\"form-control form-control-line\">\r\n");
      out.write("                                            	");
      out.print(i.getRanInt().getFecha_desde() );
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-md-12\" style=\"color: blue\">\r\n");
      out.write("                                       		<p style = \"font-family:themify;font-size:19px;font-style:normal;\">Discord ID</p>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <div class=\"col-md-12\">\r\n");
      out.write("                                            <div class=\"form-control form-control-line\">\r\n");
      out.write("                                            	");
      out.print(i.getDiscordId() );
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-md-12\" style=\"color: blue\">\r\n");
      out.write("                                        	<p style = \"font-family:themify;font-size:19px;font-style:normal;\">Steam Hex</p>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <div class=\"col-md-12\">\r\n");
      out.write("                                            <div class=\"form-control form-control-line\">\r\n");
      out.write("                                            	");
      out.print(i.getSteamHex() );
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-md-12\" style=\"color: blue\">\r\n");
      out.write("                                        	<p style = \"font-family:themify;font-size:19px;font-style:normal;\">Nombre Usuario</p>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <div class=\"col-md-12\">\r\n");
      out.write("                                            <div class=\"form-control form-control-line\">\r\n");
      out.write("                                            	");
      out.print(i.getUsuario() );
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-md-12\" style=\"color: blue\">\r\n");
      out.write("                                        	<p style = \"font-family:themify;font-size:19px;font-style:normal;\">Sub-Division</p>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <div class=\"col-md-12\">\r\n");
      out.write("                                            <div class=\"form-control form-control-line\">\r\n");
      out.write("                                            	");
 	
													if(i.getSub() != null)
													{
														out.println("Nombre sub-division: " + i.getSub().getDescripcion());  
      out.write(" <br> ");

														out.println("Rango sub-division: " + i.getSub().getRanSub().get(0).getNombreRangoSub()); 
      out.write(" <br> ");

														out.println("Fecha ultimo ascenso:" + i.getSub().getRanSub().get(0).getRsi().getFecha_desde()); 
      out.write(" <br> ");

													}  
													else 
														out.println("No tiene subdivision");
												
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-md-12\" style=\"color: blue\">\r\n");
      out.write("                                        	<p style = \"font-family:themify;font-size:19px;font-style:normal;\">Bitacoras</p>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                        <div class=\"col-sm-12\">\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"form-group\">                                    \r\n");
      out.write("                                        <div class=\"col-sm-12\">   \r\n");
      out.write("                                        <input type=\"submit\" onclick = \"mostrarForm()\"  value=\"Editar datos personales\" id=\"btn1\">                                                                                \r\n");
      out.write("                                            <form action=\"editarPerfilS\" method=\"post\" id=\"editarDatos\" hidden=\"\">\r\n");
      out.write("												Nombre: <input type = \"text\" name = \"nombre\" value=\"");
      out.print(i.getNombre());
      out.write("\"Required><br><br>\r\n");
      out.write("												Apellido: <input type = \"text\" name = \"apellido\" value=\"");
      out.print(i.getApellido());
      out.write("\"Required><br><br>\r\n");
      out.write("												Discord Id: <input type = \"text\" name = \"discordId\" value=\"");
      out.print(i.getDiscordId());
      out.write("\"Required><br><br>\r\n");
      out.write("												Usuario: <input type = \"text\" name = \"usuario\" value=\"");
      out.print(i.getUsuario());
      out.write("\"Required><br><br>\r\n");
      out.write("												Contrasenia: <input type = \"password\" name = \"pw\" placeholder=\"Obligatorio\" Required><br><br>\r\n");
      out.write("												<input type = \"submit\" value = \"Guardar cambios\" ><br><br>\r\n");
      out.write("											</form>											                                     \r\n");
      out.write("                                        </div>                                        \r\n");
      out.write("                                    </div>                                    \r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Column -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Row -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- End PAge Content -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Right sidebar -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- .right-sidebar -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- End Right sidebar -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <footer class=\"footer text-center\">\r\n");
      out.write("                Panel de la faccion de Prosegur en [BA:RP] ||\r\n");
      out.write("                    <a href=\"https://github.com/Luchoragusa\">Luciano Ragusa</a> || \r\n");
      out.write("                    <a href=\"https://github.com/JuaniPucheta\">Juan Ignacio Pucheta</a>.|| \r\n");
      out.write("                    <a href=\"https://github.com/CamiloPereyra\">Camilo Pereyra</a>.\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End Wrapper -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- All Jquery -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function mostrarForm()\r\n");
      out.write("		{\r\n");
      out.write("			document.getElementById('editarDatos').hidden=false;\r\n");
      out.write("			document.getElementById('btn1').hidden=true;\r\n");
      out.write("		}\r\n");
      out.write("	</script>  \r\n");
      out.write("    <script src=\"./assets/libs/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap tether Core JavaScript -->\r\n");
      out.write("    <script src=\"./assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"./dist/js/app-style-switcher.js\"></script>\r\n");
      out.write("    <!--Wave Effects -->\r\n");
      out.write("    <script src=\"./dist/js/waves.js\"></script>\r\n");
      out.write("    <!--Menu sidebar -->\r\n");
      out.write("    <script src=\"./dist/js/sidebarmenu.js\"></script>\r\n");
      out.write("    <!--Custom JavaScript -->\r\n");
      out.write("    <script src=\"./dist/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
